<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\City;
class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
                ["id"=>"1","governorate_id"=>"1","name"=>["ar"=>"15 مايو","en"=>"15 May"]],
                ["id"=>"2","governorate_id"=>"1","name"=>["ar"=>"الازبكية","en"=>"Al Azbakeyah"]],
                ["id"=>"3","governorate_id"=>"1","name"=>["ar"=>"البساتين","en"=>"Al Basatin"]],
                ["id"=>"4","governorate_id"=>"1","name"=>["ar"=>"التبين","en"=>"Tebin"]],
                ["id"=>"5","governorate_id"=>"1","name"=>["ar"=>"الخليفة","en"=>"El-Khalifa"]],
                ["id"=>"6","governorate_id"=>"1","name"=>["ar"=>"الدراسة","en"=>"El darrasa"]],
                ["id"=>"7","governorate_id"=>"1","name"=>["ar"=>"الدرب الاحمر","en"=>"Aldarb Alahmar"]],
                ["id"=>"8","governorate_id"=>"1","name"=>["ar"=>"الزاوية الحمراء","en"=>"Zawya al-Hamra"]],
                ["id"=>"9","governorate_id"=>"1","name"=>["ar"=>"الزيتون","en"=>"El-Zaytoun"]],
                ["id"=>"10","governorate_id"=>"1","name"=>["ar"=>"الساحل","en"=>"Sahel"]],
                ["id"=>"11","governorate_id"=>"1","name"=>["ar"=>"السلام","en"=>"El Salam"]],
                ["id"=>"12","governorate_id"=>"1","name"=>["ar"=>"السيدة زينب","en"=>"Sayeda Zeinab"]],
                ["id"=>"13","governorate_id"=>"1","name"=>["ar"=>"الشرابية","en"=>"El Sharabeya"]],
                ["id"=>"14","governorate_id"=>"1","name"=>["ar"=>"مدينة الشروق","en"=>"Shorouk"]],
                ["id"=>"15","governorate_id"=>"1","name"=>["ar"=>"الظاهر","en"=>"El Daher"]],
                ["id"=>"16","governorate_id"=>"1","name"=>["ar"=>"العتبة","en"=>"Ataba"]],
                ["id"=>"17","governorate_id"=>"1","name"=>["ar"=>"القاهرة الجديدة","en"=>"New Cairo"]],
                ["id"=>"18","governorate_id"=>"1","name"=>["ar"=>"المرج","en"=>"El Marg"]],
                ["id"=>"19","governorate_id"=>"1","name"=>["ar"=>"عزبة النخل","en"=>"Ezbet el Nakhl"]],
                ["id"=>"20","governorate_id"=>"1","name"=>["ar"=>"المطرية","en"=>"Matareya"]],
                ["id"=>"21","governorate_id"=>"1","name"=>["ar"=>"المعادى","en"=>"Maadi"]],
                ["id"=>"22","governorate_id"=>"1","name"=>["ar"=>"المعصرة","en"=>"Maasara"]],
                ["id"=>"23","governorate_id"=>"1","name"=>["ar"=>"المقطم","en"=>"Mokattam"]],
                ["id"=>"24","governorate_id"=>"1","name"=>["ar"=>"المنيل","en"=>"Manyal"]],
                ["id"=>"25","governorate_id"=>"1","name"=>["ar"=>"الموسكى","en"=>"Mosky"]],
                ["id"=>"26","governorate_id"=>"1","name"=>["ar"=>"النزهة","en"=>"Nozha"]],
                ["id"=>"27","governorate_id"=>"1","name"=>["ar"=>"الوايلى","en"=>"Waily"]],
                ["id"=>"28","governorate_id"=>"1","name"=>["ar"=>"باب الشعرية","en"=>"Bab al-Shereia"]],
                ["id"=>"29","governorate_id"=>"1","name"=>["ar"=>"بولاق","en"=>"Bolaq"]],
                ["id"=>"30","governorate_id"=>"1","name"=>["ar"=>"جاردن سيتى","en"=>"Garden City"]],
                ["id"=>"31","governorate_id"=>"1","name"=>["ar"=>"حدائق القبة","en"=>"Hadayek El-Kobba"]],
                ["id"=>"32","governorate_id"=>"1","name"=>["ar"=>"حلوان","en"=>"Helwan"]],
                ["id"=>"33","governorate_id"=>"1","name"=>["ar"=>"دار السلام","en"=>"Dar Al Salam"]],
                ["id"=>"34","governorate_id"=>"1","name"=>["ar"=>"شبرا","en"=>"Shubra"]],
                ["id"=>"35","governorate_id"=>"1","name"=>["ar"=>"طره","en"=>"Tura"]],
                ["id"=>"36","governorate_id"=>"1","name"=>["ar"=>"عابدين","en"=>"Abdeen"]],
                ["id"=>"37","governorate_id"=>"1","name"=>["ar"=>"عباسية","en"=>"Abaseya"]],
                ["id"=>"38","governorate_id"=>"1","name"=>["ar"=>"عين شمس","en"=>"Ain Shams"]],
                ["id"=>"39","governorate_id"=>"1","name"=>["ar"=>"مدينة نصر","en"=>"Nasr City"]],
                ["id"=>"40","governorate_id"=>"1","name"=>["ar"=>"مصر الجديدة","en"=>"New Heliopolis"]],
                ["id"=>"41","governorate_id"=>"1","name"=>["ar"=>"مصر القديمة","en"=>"Masr Al Qadima"]],
                ["id"=>"42","governorate_id"=>"1","name"=>["ar"=>"منشية ناصر","en"=>"Mansheya Nasir"]],
                ["id"=>"43","governorate_id"=>"1","name"=>["ar"=>"مدينة بدر","en"=>"Badr City"]],
                ["id"=>"44","governorate_id"=>"1","name"=>["ar"=>"مدينة العبور","en"=>"Obour City"]],
                ["id"=>"45","governorate_id"=>"1","name"=>["ar"=>"وسط البلد","en"=>"Cairo Downtown"]],
                ["id"=>"46","governorate_id"=>"1","name"=>["ar"=>"الزمالك","en"=>"Zamalek"]],
                ["id"=>"47","governorate_id"=>"1","name"=>["ar"=>"قصر النيل","en"=>"Kasr El Nile"]],
                ["id"=>"48","governorate_id"=>"1","name"=>["ar"=>"الرحاب","en"=>"Rehab"]],
                ["id"=>"49","governorate_id"=>"1","name"=>["ar"=>"القطامية","en"=>"Katameya"]],
                ["id"=>"50","governorate_id"=>"1","name"=>["ar"=>"مدينتي","en"=>"Madinty"]],
                ["id"=>"51","governorate_id"=>"1","name"=>["ar"=>"روض الفرج","en"=>"Rod Alfarag"]],
                ["id"=>"52","governorate_id"=>"1","name"=>["ar"=>"شيراتون","en"=>"Sheraton"]],
                ["id"=>"53","governorate_id"=>"1","name"=>["ar"=>"الجمالية","en"=>"El-Gamaleya"]],
                ["id"=>"54","governorate_id"=>"1","name"=>["ar"=>"العاشر من رمضان","en"=>"10th of Ramadan City"]],
                ["id"=>"55","governorate_id"=>"1","name"=>["ar"=>"الحلمية","en"=>"Helmeyat Alzaytoun"]],
                ["id"=>"56","governorate_id"=>"1","name"=>["ar"=>"النزهة الجديدة","en"=>"New Nozha"]],
                ["id"=>"57","governorate_id"=>"1","name"=>["ar"=>"العاصمة الإدارية","en"=>"Capital New"]],
                ["id"=>"58","governorate_id"=>"2","name"=>["ar"=>"الجيزة","en"=>"Giza"]],
                ["id"=>"59","governorate_id"=>"2","name"=>["ar"=>"السادس من أكتوبر","en"=>"Sixth of October"]],
                ["id"=>"60","governorate_id"=>"2","name"=>["ar"=>"الشيخ زايد","en"=>"Cheikh Zayed"]],
                ["id"=>"61","governorate_id"=>"2","name"=>["ar"=>"الحوامدية","en"=>"Hawamdiyah"]],
                ["id"=>"62","governorate_id"=>"2","name"=>["ar"=>"البدرشين","en"=>"Al Badrasheen"]],
                ["id"=>"63","governorate_id"=>"2","name"=>["ar"=>"الصف","en"=>"Saf"]],
                ["id"=>"64","governorate_id"=>"2","name"=>["ar"=>"أطفيح","en"=>"Atfih"]],
                ["id"=>"65","governorate_id"=>"2","name"=>["ar"=>"العياط","en"=>"Al Ayat"]],
                ["id"=>"66","governorate_id"=>"2","name"=>["ar"=>"الباويطي","en"=>"Al-Bawaiti"]],
                ["id"=>"67","governorate_id"=>"2","name"=>["ar"=>"منشأة القناطر","en"=>"ManshiyetAl Qanater"]],
                ["id"=>"68","governorate_id"=>"2","name"=>["ar"=>"أوسيم","en"=>"Oaseem"]],
                ["id"=>"69","governorate_id"=>"2","name"=>["ar"=>"كرداسة","en"=>"Kerdasa"]],
                ["id"=>"70","governorate_id"=>"2","name"=>["ar"=>"أبو النمرس","en"=>"Abu Nomros"]],
                ["id"=>"71","governorate_id"=>"2","name"=>["ar"=>"كفر غطاطي","en"=>"Kafr Ghati"]],
                ["id"=>"72","governorate_id"=>"2","name"=>["ar"=>"منشأة البكاري","en"=>"Manshiyet Al Bakari"]],
                ["id"=>"73","governorate_id"=>"2","name"=>["ar"=>"الدقى","en"=>"Dokki"]],
                ["id"=>"74","governorate_id"=>"2","name"=>["ar"=>"العجوزة","en"=>"Agouza"]],
                ["id"=>"75","governorate_id"=>"2","name"=>["ar"=>"الهرم","en"=>"Haram"]],
                ["id"=>"76","governorate_id"=>"2","name"=>["ar"=>"الوراق","en"=>"Warraq"]],
                ["id"=>"77","governorate_id"=>"2","name"=>["ar"=>"امبابة","en"=>"Imbaba"]],
                ["id"=>"78","governorate_id"=>"2","name"=>["ar"=>"بولاق الدكرور","en"=>"Boulaq Dakrour"]],
                ["id"=>"79","governorate_id"=>"2","name"=>["ar"=>"الواحات البحرية","en"=>"Al Wahat Al Baharia"]],
                ["id"=>"80","governorate_id"=>"2","name"=>["ar"=>"العمرانية","en"=>"Omraneya"]],
                ["id"=>"81","governorate_id"=>"2","name"=>["ar"=>"المنيب","en"=>"Moneeb"]],
                ["id"=>"82","governorate_id"=>"2","name"=>["ar"=>"بين السرايات","en"=>"Bin Alsarayat"]],
                ["id"=>"83","governorate_id"=>"2","name"=>["ar"=>"الكيت كات","en"=>"Kit Kat"]],
                ["id"=>"84","governorate_id"=>"2","name"=>["ar"=>"المهندسين","en"=>"Mohandessin"]],
                ["id"=>"85","governorate_id"=>"2","name"=>["ar"=>"فيصل","en"=>"Faisal"]],
                ["id"=>"86","governorate_id"=>"2","name"=>["ar"=>"أبو رواش","en"=>"Abu Rawash"]],
                ["id"=>"87","governorate_id"=>"2","name"=>["ar"=>"حدائق الأهرام","en"=>"Hadayek Alahram"]],
                ["id"=>"88","governorate_id"=>"2","name"=>["ar"=>"الحرانية","en"=>"Haraneya"]],
                ["id"=>"89","governorate_id"=>"2","name"=>["ar"=>"حدائق اكتوبر","en"=>"Hadayek October"]],
                ["id"=>"90","governorate_id"=>"2","name"=>["ar"=>"صفط اللبن","en"=>"Saft Allaban"]],
                ["id"=>"91","governorate_id"=>"2","name"=>["ar"=>"القرية الذكية","en"=>"Smart Village"]],
                ["id"=>"92","governorate_id"=>"2","name"=>["ar"=>"ارض اللواء","en"=>"Ard Ellwaa"]],
                ["id"=>"93","governorate_id"=>"3","name"=>["ar"=>"ابو قير","en"=>"Abu Qir"]],
                ["id"=>"94","governorate_id"=>"3","name"=>["ar"=>"الابراهيمية","en"=>"Al Ibrahimeyah"]],
                ["id"=>"95","governorate_id"=>"3","name"=>["ar"=>"الأزاريطة","en"=>"Azarita"]],
                ["id"=>"96","governorate_id"=>"3","name"=>["ar"=>"الانفوشى","en"=>"Anfoushi"]],
                ["id"=>"97","governorate_id"=>"3","name"=>["ar"=>"الدخيلة","en"=>"Dekheila"]],
                ["id"=>"98","governorate_id"=>"3","name"=>["ar"=>"السيوف","en"=>"El Soyof"]],
                ["id"=>"99","governorate_id"=>"3","name"=>["ar"=>"العامرية","en"=>"Ameria"]],
                ["id"=>"100","governorate_id"=>"3","name"=>["ar"=>"اللبان","en"=>"El Labban"]],
                ["id"=>"101","governorate_id"=>"3","name"=>["ar"=>"المفروزة","en"=>"Al Mafrouza"]],
                ["id"=>"102","governorate_id"=>"3","name"=>["ar"=>"المنتزه","en"=>"El Montaza"]],
                ["id"=>"103","governorate_id"=>"3","name"=>["ar"=>"المنشية","en"=>"Mansheya"]],
                ["id"=>"104","governorate_id"=>"3","name"=>["ar"=>"الناصرية","en"=>"Naseria"]],
                ["id"=>"105","governorate_id"=>"3","name"=>["ar"=>"امبروزو","en"=>"Ambrozo"]],
                ["id"=>"106","governorate_id"=>"3","name"=>["ar"=>"باب شرق","en"=>"Bab Sharq"]],
                ["id"=>"107","governorate_id"=>"3","name"=>["ar"=>"برج العرب","en"=>"Bourj Alarab"]],
                ["id"=>"108","governorate_id"=>"3","name"=>["ar"=>"ستانلى","en"=>"Stanley"]],
                ["id"=>"109","governorate_id"=>"3","name"=>["ar"=>"سموحة","en"=>"Smouha"]],
                ["id"=>"110","governorate_id"=>"3","name"=>["ar"=>"سيدى بشر","en"=>"Sidi Bishr"]],
                ["id"=>"111","governorate_id"=>"3","name"=>["ar"=>"شدس","en"=>"Shads"]],
                ["id"=>"112","governorate_id"=>"3","name"=>["ar"=>"غيط العنب","en"=>"Gheet Alenab"]],
                ["id"=>"113","governorate_id"=>"3","name"=>["ar"=>"فلمينج","en"=>"Fleming"]],
                ["id"=>"114","governorate_id"=>"3","name"=>["ar"=>"فيكتوريا","en"=>"Victoria"]],
                ["id"=>"115","governorate_id"=>"3","name"=>["ar"=>"كامب شيزار","en"=>"Camp Shizar"]],
                ["id"=>"116","governorate_id"=>"3","name"=>["ar"=>"كرموز","en"=>"Karmooz"]],
                ["id"=>"117","governorate_id"=>"3","name"=>["ar"=>"محطة الرمل","en"=>"Mahta Alraml"]],
                ["id"=>"118","governorate_id"=>"3","name"=>["ar"=>"مينا البصل","en"=>"Mina El-Basal"]],
                ["id"=>"119","governorate_id"=>"3","name"=>["ar"=>"العصافرة","en"=>"Asafra"]],
                ["id"=>"120","governorate_id"=>"3","name"=>["ar"=>"العجمي","en"=>"Agamy"]],
                ["id"=>"121","governorate_id"=>"3","name"=>["ar"=>"بكوس","en"=>"Bakos"]],
                ["id"=>"122","governorate_id"=>"3","name"=>["ar"=>"بولكلي","en"=>"Boulkly"]],
                ["id"=>"123","governorate_id"=>"3","name"=>["ar"=>"كليوباترا","en"=>"Cleopatra"]],
                ["id"=>"124","governorate_id"=>"3","name"=>["ar"=>"جليم","en"=>"Glim"]],
                ["id"=>"125","governorate_id"=>"3","name"=>["ar"=>"المعمورة","en"=>"Al Mamurah"]],
                ["id"=>"126","governorate_id"=>"3","name"=>["ar"=>"المندرة","en"=>"Al Mandara"]],
                ["id"=>"127","governorate_id"=>"3","name"=>["ar"=>"محرم بك","en"=>"Moharam Bek"]],
                ["id"=>"128","governorate_id"=>"3","name"=>["ar"=>"الشاطبي","en"=>"Elshatby"]],
                ["id"=>"129","governorate_id"=>"3","name"=>["ar"=>"سيدي جابر","en"=>"Sidi Gaber"]],
                ["id"=>"130","governorate_id"=>"3","name"=>["ar"=>"الساحل الشمالي","en"=>"North Coast\/sahel"]],
                ["id"=>"131","governorate_id"=>"3","name"=>["ar"=>"الحضرة","en"=>"Alhadra"]],
                ["id"=>"132","governorate_id"=>"3","name"=>["ar"=>"العطارين","en"=>"Alattarin"]],
                ["id"=>"133","governorate_id"=>"3","name"=>["ar"=>"سيدي كرير","en"=>"Sidi Kerir"]],
                ["id"=>"134","governorate_id"=>"3","name"=>["ar"=>"الجمرك","en"=>"Elgomrok"]],
                ["id"=>"135","governorate_id"=>"3","name"=>["ar"=>"المكس","en"=>"Al Max"]],
                ["id"=>"136","governorate_id"=>"3","name"=>["ar"=>"مارينا","en"=>"Marina"]],
                ["id"=>"137","governorate_id"=>"4","name"=>["ar"=>"المنصورة","en"=>"Mansoura"]],
                ["id"=>"138","governorate_id"=>"4","name"=>["ar"=>"طلخا","en"=>"Talkha"]],
                ["id"=>"139","governorate_id"=>"4","name"=>["ar"=>"ميت غمر","en"=>"Mitt Ghamr"]],
                ["id"=>"140","governorate_id"=>"4","name"=>["ar"=>"دكرنس","en"=>"Dekernes"]],
                ["id"=>"141","governorate_id"=>"4","name"=>["ar"=>"أجا","en"=>"Aga"]],
                ["id"=>"142","governorate_id"=>"4","name"=>["ar"=>"منية النصر","en"=>"Menia El Nasr"]],
                ["id"=>"143","governorate_id"=>"4","name"=>["ar"=>"السنبلاوين","en"=>"Sinbillawin"]],
                ["id"=>"144","governorate_id"=>"4","name"=>["ar"=>"الكردي","en"=>"El Kurdi"]],
                ["id"=>"145","governorate_id"=>"4","name"=>["ar"=>"بني عبيد","en"=>"Bani Ubaid"]],
                ["id"=>"146","governorate_id"=>"4","name"=>["ar"=>"المنزلة","en"=>"Al Manzala"]],
                ["id"=>"147","governorate_id"=>"4","name"=>["ar"=>"تمي الأمديد","en"=>"tami al'amdid"]],
                ["id"=>"148","governorate_id"=>"4","name"=>["ar"=>"الجمالية","en"=>"aljamalia"]],
                ["id"=>"149","governorate_id"=>"4","name"=>["ar"=>"شربين","en"=>"Sherbin"]],
                ["id"=>"150","governorate_id"=>"4","name"=>["ar"=>"المطرية","en"=>"Mataria"]],
                ["id"=>"151","governorate_id"=>"4","name"=>["ar"=>"بلقاس","en"=>"Belqas"]],
                ["id"=>"152","governorate_id"=>"4","name"=>["ar"=>"ميت سلسيل","en"=>"Meet Salsil"]],
                ["id"=>"153","governorate_id"=>"4","name"=>["ar"=>"جمصة","en"=>"Gamasa"]],
                ["id"=>"154","governorate_id"=>"4","name"=>["ar"=>"محلة دمنة","en"=>"Mahalat Damana"]],
                ["id"=>"155","governorate_id"=>"4","name"=>["ar"=>"نبروه","en"=>"Nabroh"]],
                ["id"=>"156","governorate_id"=>"5","name"=>["ar"=>"الغردقة","en"=>"Hurghada"]],
                ["id"=>"157","governorate_id"=>"5","name"=>["ar"=>"رأس غارب","en"=>"Ras Ghareb"]],
                ["id"=>"158","governorate_id"=>"5","name"=>["ar"=>"سفاجا","en"=>"Safaga"]],
                ["id"=>"159","governorate_id"=>"5","name"=>["ar"=>"القصير","en"=>"El Qusiar"]],
                ["id"=>"160","governorate_id"=>"5","name"=>["ar"=>"مرسى علم","en"=>"Marsa Alam"]],
                ["id"=>"161","governorate_id"=>"5","name"=>["ar"=>"الشلاتين","en"=>"Shalatin"]],
                ["id"=>"162","governorate_id"=>"5","name"=>["ar"=>"حلايب","en"=>"Halaib"]],
                ["id"=>"163","governorate_id"=>"5","name"=>["ar"=>"الدهار","en"=>"Aldahar"]],
                ["id"=>"164","governorate_id"=>"6","name"=>["ar"=>"دمنهور","en"=>"Damanhour"]],
                ["id"=>"165","governorate_id"=>"6","name"=>["ar"=>"كفر الدوار","en"=>"Kafr El Dawar"]],
                ["id"=>"166","governorate_id"=>"6","name"=>["ar"=>"رشيد","en"=>"Rashid"]],
                ["id"=>"167","governorate_id"=>"6","name"=>["ar"=>"إدكو","en"=>"Edco"]],
                ["id"=>"168","governorate_id"=>"6","name"=>["ar"=>"أبو المطامير","en"=>"Abu al-Matamir"]],
                ["id"=>"169","governorate_id"=>"6","name"=>["ar"=>"أبو حمص","en"=>"Abu Homs"]],
                ["id"=>"170","governorate_id"=>"6","name"=>["ar"=>"الدلنجات","en"=>"Delengat"]],
                ["id"=>"171","governorate_id"=>"6","name"=>["ar"=>"المحمودية","en"=>"Mahmoudiyah"]],
                ["id"=>"172","governorate_id"=>"6","name"=>["ar"=>"الرحمانية","en"=>"Rahmaniyah"]],
                ["id"=>"173","governorate_id"=>"6","name"=>["ar"=>"إيتاي البارود","en"=>"Itai Baroud"]],
                ["id"=>"174","governorate_id"=>"6","name"=>["ar"=>"حوش عيسى","en"=>"Housh Eissa"]],
                ["id"=>"175","governorate_id"=>"6","name"=>["ar"=>"شبراخيت","en"=>"Shubrakhit"]],
                ["id"=>"176","governorate_id"=>"6","name"=>["ar"=>"كوم حمادة","en"=>"Kom Hamada"]],
                ["id"=>"177","governorate_id"=>"6","name"=>["ar"=>"بدر","en"=>"Badr"]],
                ["id"=>"178","governorate_id"=>"6","name"=>["ar"=>"وادي النطرون","en"=>"Wadi Natrun"]],
                ["id"=>"179","governorate_id"=>"6","name"=>["ar"=>"النوبارية الجديدة","en"=>"New Nubaria"]],
                ["id"=>"180","governorate_id"=>"6","name"=>["ar"=>"النوبارية","en"=>"Alnoubareya"]],
                ["id"=>"181","governorate_id"=>"7","name"=>["ar"=>"الفيوم","en"=>"Fayoum"]],
                ["id"=>"182","governorate_id"=>"7","name"=>["ar"=>"الفيوم الجديدة","en"=>"Fayoum El Gedida"]],
                ["id"=>"183","governorate_id"=>"7","name"=>["ar"=>"طامية","en"=>"Tamiya"]],
                ["id"=>"184","governorate_id"=>"7","name"=>["ar"=>"سنورس","en"=>"Snores"]],
                ["id"=>"185","governorate_id"=>"7","name"=>["ar"=>"إطسا","en"=>"Etsa"]],
                ["id"=>"186","governorate_id"=>"7","name"=>["ar"=>"إبشواي","en"=>"Epschway"]],
                ["id"=>"187","governorate_id"=>"7","name"=>["ar"=>"يوسف الصديق","en"=>"Yusuf El Sediaq"]],
                ["id"=>"188","governorate_id"=>"7","name"=>["ar"=>"الحادقة","en"=>"Hadqa"]],
                ["id"=>"189","governorate_id"=>"7","name"=>["ar"=>"اطسا","en"=>"Atsa"]],
                ["id"=>"190","governorate_id"=>"7","name"=>["ar"=>"الجامعة","en"=>"Algamaa"]],
                ["id"=>"191","governorate_id"=>"7","name"=>["ar"=>"السيالة","en"=>"Sayala"]],
                ["id"=>"192","governorate_id"=>"8","name"=>["ar"=>"طنطا","en"=>"Tanta"]],
                ["id"=>"193","governorate_id"=>"8","name"=>["ar"=>"المحلة الكبرى","en"=>"Al Mahalla Al Kobra"]],
                ["id"=>"194","governorate_id"=>"8","name"=>["ar"=>"كفر الزيات","en"=>"Kafr El Zayat"]],
                ["id"=>"195","governorate_id"=>"8","name"=>["ar"=>"زفتى","en"=>"Zefta"]],
                ["id"=>"196","governorate_id"=>"8","name"=>["ar"=>"السنطة","en"=>"El Santa"]],
                ["id"=>"197","governorate_id"=>"8","name"=>["ar"=>"قطور","en"=>"Qutour"]],
                ["id"=>"198","governorate_id"=>"8","name"=>["ar"=>"بسيون","en"=>"Basion"]],
                ["id"=>"199","governorate_id"=>"8","name"=>["ar"=>"سمنود","en"=>"Samannoud"]],
                ["id"=>"200","governorate_id"=>"9","name"=>["ar"=>"الإسماعيلية","en"=>"Ismailia"]],
                ["id"=>"201","governorate_id"=>"9","name"=>["ar"=>"فايد","en"=>"Fayed"]],
                ["id"=>"202","governorate_id"=>"9","name"=>["ar"=>"القنطرة شرق","en"=>"Qantara Sharq"]],
                ["id"=>"203","governorate_id"=>"9","name"=>["ar"=>"القنطرة غرب","en"=>"Qantara Gharb"]],
                ["id"=>"204","governorate_id"=>"9","name"=>["ar"=>"التل الكبير","en"=>"El Tal El Kabier"]],
                ["id"=>"205","governorate_id"=>"9","name"=>["ar"=>"أبو صوير","en"=>"Abu Sawir"]],
                ["id"=>"206","governorate_id"=>"9","name"=>["ar"=>"القصاصين الجديدة","en"=>"Kasasien El Gedida"]],
                ["id"=>"207","governorate_id"=>"9","name"=>["ar"=>"نفيشة","en"=>"Nefesha"]],
                ["id"=>"208","governorate_id"=>"9","name"=>["ar"=>"الشيخ زايد","en"=>"Sheikh Zayed"]],
                ["id"=>"209","governorate_id"=>"10","name"=>["ar"=>"شبين الكوم","en"=>"Shbeen El Koom"]],
                ["id"=>"210","governorate_id"=>"10","name"=>["ar"=>"مدينة السادات","en"=>"Sadat City"]],
                ["id"=>"211","governorate_id"=>"10","name"=>["ar"=>"منوف","en"=>"Menouf"]],
                ["id"=>"212","governorate_id"=>"10","name"=>["ar"=>"سرس الليان","en"=>"Sars El-Layan"]],
                ["id"=>"213","governorate_id"=>"10","name"=>["ar"=>"أشمون","en"=>"Ashmon"]],
                ["id"=>"214","governorate_id"=>"10","name"=>["ar"=>"الباجور","en"=>"Al Bagor"]],
                ["id"=>"215","governorate_id"=>"10","name"=>["ar"=>"قويسنا","en"=>"Quesna"]],
                ["id"=>"216","governorate_id"=>"10","name"=>["ar"=>"بركة السبع","en"=>"Berkat El Saba"]],
                ["id"=>"217","governorate_id"=>"10","name"=>["ar"=>"تلا","en"=>"Tala"]],
                ["id"=>"218","governorate_id"=>"10","name"=>["ar"=>"الشهداء","en"=>"Al Shohada"]],
                ["id"=>"219","governorate_id"=>"11","name"=>["ar"=>"المنيا","en"=>"Minya"]],
                ["id"=>"220","governorate_id"=>"11","name"=>["ar"=>"المنيا الجديدة","en"=>"Minya El Gedida"]],
                ["id"=>"221","governorate_id"=>"11","name"=>["ar"=>"العدوة","en"=>"El Adwa"]],
                ["id"=>"222","governorate_id"=>"11","name"=>["ar"=>"مغاغة","en"=>"Magagha"]],
                ["id"=>"223","governorate_id"=>"11","name"=>["ar"=>"بني مزار","en"=>"Bani Mazar"]],
                ["id"=>"224","governorate_id"=>"11","name"=>["ar"=>"مطاي","en"=>"Mattay"]],
                ["id"=>"225","governorate_id"=>"11","name"=>["ar"=>"سمالوط","en"=>"Samalut"]],
                ["id"=>"226","governorate_id"=>"11","name"=>["ar"=>"المدينة الفكرية","en"=>"Madinat El Fekria"]],
                ["id"=>"227","governorate_id"=>"11","name"=>["ar"=>"ملوي","en"=>"Meloy"]],
                ["id"=>"228","governorate_id"=>"11","name"=>["ar"=>"دير مواس","en"=>"Deir Mawas"]],
                ["id"=>"229","governorate_id"=>"11","name"=>["ar"=>"ابو قرقاص","en"=>"Abu Qurqas"]],
                ["id"=>"230","governorate_id"=>"11","name"=>["ar"=>"ارض سلطان","en"=>"Ard Sultan"]],
                ["id"=>"231","governorate_id"=>"12","name"=>["ar"=>"بنها","en"=>"Banha"]],
                ["id"=>"232","governorate_id"=>"12","name"=>["ar"=>"قليوب","en"=>"Qalyub"]],
                ["id"=>"233","governorate_id"=>"12","name"=>["ar"=>"شبرا الخيمة","en"=>"Shubra Al Khaimah"]],
                ["id"=>"234","governorate_id"=>"12","name"=>["ar"=>"القناطر الخيرية","en"=>"Al Qanater Charity"]],
                ["id"=>"235","governorate_id"=>"12","name"=>["ar"=>"الخانكة","en"=>"Khanka"]],
                ["id"=>"236","governorate_id"=>"12","name"=>["ar"=>"كفر شكر","en"=>"Kafr Shukr"]],
                ["id"=>"237","governorate_id"=>"12","name"=>["ar"=>"طوخ","en"=>"Tukh"]],
                ["id"=>"238","governorate_id"=>"12","name"=>["ar"=>"قها","en"=>"Qaha"]],
                ["id"=>"239","governorate_id"=>"12","name"=>["ar"=>"العبور","en"=>"Obour"]],
                ["id"=>"240","governorate_id"=>"12","name"=>["ar"=>"الخصوص","en"=>"Khosous"]],
                ["id"=>"241","governorate_id"=>"12","name"=>["ar"=>"شبين القناطر","en"=>"Shibin Al Qanater"]],
                ["id"=>"242","governorate_id"=>"12","name"=>["ar"=>"مسطرد","en"=>"Mostorod"]],
                ["id"=>"243","governorate_id"=>"13","name"=>["ar"=>"الخارجة","en"=>"El Kharga"]],
                ["id"=>"244","governorate_id"=>"13","name"=>["ar"=>"باريس","en"=>"Paris"]],
                ["id"=>"245","governorate_id"=>"13","name"=>["ar"=>"موط","en"=>"Mout"]],
                ["id"=>"246","governorate_id"=>"13","name"=>["ar"=>"الفرافرة","en"=>"Farafra"]],
                ["id"=>"247","governorate_id"=>"13","name"=>["ar"=>"بلاط","en"=>"Balat"]],
                ["id"=>"248","governorate_id"=>"13","name"=>["ar"=>"الداخلة","en"=>"Dakhla"]],
                ["id"=>"249","governorate_id"=>"14","name"=>["ar"=>"السويس","en"=>"Suez"]],
                ["id"=>"250","governorate_id"=>"14","name"=>["ar"=>"الجناين","en"=>"Alganayen"]],
                ["id"=>"251","governorate_id"=>"14","name"=>["ar"=>"عتاقة","en"=>"Ataqah"]],
                ["id"=>"252","governorate_id"=>"14","name"=>["ar"=>"العين السخنة","en"=>"Ain Sokhna"]],
                ["id"=>"253","governorate_id"=>"14","name"=>["ar"=>"فيصل","en"=>"Faysal"]],
                ["id"=>"254","governorate_id"=>"15","name"=>["ar"=>"أسوان","en"=>"Aswan"]],
                ["id"=>"255","governorate_id"=>"15","name"=>["ar"=>"أسوان الجديدة","en"=>"Aswan El Gedida"]],
                ["id"=>"256","governorate_id"=>"15","name"=>["ar"=>"دراو","en"=>"Drau"]],
                ["id"=>"257","governorate_id"=>"15","name"=>["ar"=>"كوم أمبو","en"=>"Kom Ombo"]],
                ["id"=>"258","governorate_id"=>"15","name"=>["ar"=>"نصر النوبة","en"=>"Nasr Al Nuba"]],
                ["id"=>"259","governorate_id"=>"15","name"=>["ar"=>"كلابشة","en"=>"Kalabsha"]],
                ["id"=>"260","governorate_id"=>"15","name"=>["ar"=>"إدفو","en"=>"Edfu"]],
                ["id"=>"261","governorate_id"=>"15","name"=>["ar"=>"الرديسية","en"=>"Al-Radisiyah"]],
                ["id"=>"262","governorate_id"=>"15","name"=>["ar"=>"البصيلية","en"=>"Al Basilia"]],
                ["id"=>"263","governorate_id"=>"15","name"=>["ar"=>"السباعية","en"=>"Al Sibaeia"]],
                ["id"=>"264","governorate_id"=>"15","name"=>["ar"=>"ابوسمبل السياحية","en"=>"Abo Simbl Al Siyahia"]],
                ["id"=>"265","governorate_id"=>"15","name"=>["ar"=>"مرسى علم","en"=>"Marsa Alam"]],
                ["id"=>"266","governorate_id"=>"16","name"=>["ar"=>"أسيوط","en"=>"Assiut"]],
                ["id"=>"267","governorate_id"=>"16","name"=>["ar"=>"أسيوط الجديدة","en"=>"Assiut El Gedida"]],
                ["id"=>"268","governorate_id"=>"16","name"=>["ar"=>"ديروط","en"=>"Dayrout"]],
                ["id"=>"269","governorate_id"=>"16","name"=>["ar"=>"منفلوط","en"=>"Manfalut"]],
                ["id"=>"270","governorate_id"=>"16","name"=>["ar"=>"القوصية","en"=>"Qusiya"]],
                ["id"=>"271","governorate_id"=>"16","name"=>["ar"=>"أبنوب","en"=>"Abnoub"]],
                ["id"=>"272","governorate_id"=>"16","name"=>["ar"=>"أبو تيج","en"=>"Abu Tig"]],
                ["id"=>"273","governorate_id"=>"16","name"=>["ar"=>"الغنايم","en"=>"El Ghanaim"]],
                ["id"=>"274","governorate_id"=>"16","name"=>["ar"=>"ساحل سليم","en"=>"Sahel Selim"]],
                ["id"=>"275","governorate_id"=>"16","name"=>["ar"=>"البداري","en"=>"El Badari"]],
                ["id"=>"276","governorate_id"=>"16","name"=>["ar"=>"صدفا","en"=>"Sidfa"]],
                ["id"=>"277","governorate_id"=>"17","name"=>["ar"=>"بني سويف","en"=>"Bani Sweif"]],
                ["id"=>"278","governorate_id"=>"17","name"=>["ar"=>"بني سويف الجديدة","en"=>"Beni Suef El Gedida"]],
                ["id"=>"279","governorate_id"=>"17","name"=>["ar"=>"الواسطى","en"=>"Al Wasta"]],
                ["id"=>"280","governorate_id"=>"17","name"=>["ar"=>"ناصر","en"=>"Naser"]],
                ["id"=>"281","governorate_id"=>"17","name"=>["ar"=>"إهناسيا","en"=>"Ehnasia"]],
                ["id"=>"282","governorate_id"=>"17","name"=>["ar"=>"ببا","en"=>"beba"]],
                ["id"=>"283","governorate_id"=>"17","name"=>["ar"=>"الفشن","en"=>"Fashn"]],
                ["id"=>"284","governorate_id"=>"17","name"=>["ar"=>"سمسطا","en"=>"Somasta"]],
                ["id"=>"285","governorate_id"=>"17","name"=>["ar"=>"الاباصيرى","en"=>"Alabbaseri"]],
                ["id"=>"286","governorate_id"=>"17","name"=>["ar"=>"مقبل","en"=>"Mokbel"]],
                ["id"=>"287","governorate_id"=>"18","name"=>["ar"=>"بورسعيد","en"=>"PorSaid"]],
                ["id"=>"288","governorate_id"=>"18","name"=>["ar"=>"بورفؤاد","en"=>"Port Fouad"]],
                ["id"=>"289","governorate_id"=>"18","name"=>["ar"=>"العرب","en"=>"Alarab"]],
                ["id"=>"290","governorate_id"=>"18","name"=>["ar"=>"حى الزهور","en"=>"Zohour"]],
                ["id"=>"291","governorate_id"=>"18","name"=>["ar"=>"حى الشرق","en"=>"Alsharq"]],
                ["id"=>"292","governorate_id"=>"18","name"=>["ar"=>"حى الضواحى","en"=>"Aldawahi"]],
                ["id"=>"293","governorate_id"=>"18","name"=>["ar"=>"حى المناخ","en"=>"Almanakh"]],
                ["id"=>"294","governorate_id"=>"18","name"=>["ar"=>"حى مبارك","en"=>"Mubarak"]],
                ["id"=>"295","governorate_id"=>"19","name"=>["ar"=>"دمياط","en"=>"Damietta"]],
                ["id"=>"296","governorate_id"=>"19","name"=>["ar"=>"دمياط الجديدة","en"=>"New Damietta"]],
                ["id"=>"297","governorate_id"=>"19","name"=>["ar"=>"رأس البر","en"=>"Ras El Bar"]],
                ["id"=>"298","governorate_id"=>"19","name"=>["ar"=>"فارسكور","en"=>"Faraskour"]],
                ["id"=>"299","governorate_id"=>"19","name"=>["ar"=>"الزرقا","en"=>"Zarqa"]],
                ["id"=>"300","governorate_id"=>"19","name"=>["ar"=>"السرو","en"=>"alsaru"]],
                ["id"=>"301","governorate_id"=>"19","name"=>["ar"=>"الروضة","en"=>"alruwda"]],
                ["id"=>"302","governorate_id"=>"19","name"=>["ar"=>"كفر البطيخ","en"=>"Kafr El-Batikh"]],
                ["id"=>"303","governorate_id"=>"19","name"=>["ar"=>"عزبة البرج","en"=>"Azbet Al Burg"]],
                ["id"=>"304","governorate_id"=>"19","name"=>["ar"=>"ميت أبو غالب","en"=>"Meet Abou Ghalib"]],
                ["id"=>"305","governorate_id"=>"19","name"=>["ar"=>"كفر سعد","en"=>"Kafr Saad"]],
                ["id"=>"306","governorate_id"=>"20","name"=>["ar"=>"الزقازيق","en"=>"Zagazig"]],
                ["id"=>"307","governorate_id"=>"20","name"=>["ar"=>"العاشر من رمضان","en"=>"Al Ashr Men Ramadan"]],
                ["id"=>"308","governorate_id"=>"20","name"=>["ar"=>"منيا القمح","en"=>"Minya Al Qamh"]],
                ["id"=>"309","governorate_id"=>"20","name"=>["ar"=>"بلبيس","en"=>"Belbeis"]],
                ["id"=>"310","governorate_id"=>"20","name"=>["ar"=>"مشتول السوق","en"=>"Mashtoul El Souq"]],
                ["id"=>"311","governorate_id"=>"20","name"=>["ar"=>"القنايات","en"=>"Qenaiat"]],
                ["id"=>"312","governorate_id"=>"20","name"=>["ar"=>"أبو حماد","en"=>"Abu Hammad"]],
                ["id"=>"313","governorate_id"=>"20","name"=>["ar"=>"القرين","en"=>"El Qurain"]],
                ["id"=>"314","governorate_id"=>"20","name"=>["ar"=>"ههيا","en"=>"Hehia"]],
                ["id"=>"315","governorate_id"=>"20","name"=>["ar"=>"أبو كبير","en"=>"Abu Kabir"]],
                ["id"=>"316","governorate_id"=>"20","name"=>["ar"=>"فاقوس","en"=>"Faccus"]],
                ["id"=>"317","governorate_id"=>"20","name"=>["ar"=>"الصالحية الجديدة","en"=>"El Salihia El Gedida"]],
                ["id"=>"318","governorate_id"=>"20","name"=>["ar"=>"الإبراهيمية","en"=>"Al Ibrahimiyah"]],
                ["id"=>"319","governorate_id"=>"20","name"=>["ar"=>"ديرب نجم","en"=>"Deirb Negm"]],
                ["id"=>"320","governorate_id"=>"20","name"=>["ar"=>"كفر صقر","en"=>"Kafr Saqr"]],
                ["id"=>"321","governorate_id"=>"20","name"=>["ar"=>"أولاد صقر","en"=>"Awlad Saqr"]],
                ["id"=>"322","governorate_id"=>"20","name"=>["ar"=>"الحسينية","en"=>"Husseiniya"]],
                ["id"=>"323","governorate_id"=>"20","name"=>["ar"=>"صان الحجر القبلية","en"=>"san alhajar alqablia"]],
                ["id"=>"324","governorate_id"=>"20","name"=>["ar"=>"منشأة أبو عمر","en"=>"Manshayat Abu Omar"]],
                ["id"=>"325","governorate_id"=>"21","name"=>["ar"=>"الطور","en"=>"Al Toor"]],
                ["id"=>"326","governorate_id"=>"21","name"=>["ar"=>"شرم الشيخ","en"=>"Sharm El-Shaikh"]],
                ["id"=>"327","governorate_id"=>"21","name"=>["ar"=>"دهب","en"=>"Dahab"]],
                ["id"=>"328","governorate_id"=>"21","name"=>["ar"=>"نويبع","en"=>"Nuweiba"]],
                ["id"=>"329","governorate_id"=>"21","name"=>["ar"=>"طابا","en"=>"Taba"]],
                ["id"=>"330","governorate_id"=>"21","name"=>["ar"=>"سانت كاترين","en"=>"Saint Catherine"]],
                ["id"=>"331","governorate_id"=>"21","name"=>["ar"=>"أبو رديس","en"=>"Abu Redis"]],
                ["id"=>"332","governorate_id"=>"21","name"=>["ar"=>"أبو زنيمة","en"=>"Abu Zenaima"]],
                ["id"=>"333","governorate_id"=>"21","name"=>["ar"=>"رأس سدر","en"=>"Ras Sidr"]],
                ["id"=>"334","governorate_id"=>"22","name"=>["ar"=>"كفر الشيخ","en"=>"Kafr El Sheikh"]],
                ["id"=>"335","governorate_id"=>"22","name"=>["ar"=>"وسط البلد كفر الشيخ","en"=>"Kafr El Sheikh Downtown"]],
                ["id"=>"336","governorate_id"=>"22","name"=>["ar"=>"دسوق","en"=>"Desouq"]],
                ["id"=>"337","governorate_id"=>"22","name"=>["ar"=>"فوه","en"=>"Fooh"]],
                ["id"=>"338","governorate_id"=>"22","name"=>["ar"=>"مطوبس","en"=>"Metobas"]],
                ["id"=>"339","governorate_id"=>"22","name"=>["ar"=>"برج البرلس","en"=>"Burg Al Burullus"]],
                ["id"=>"340","governorate_id"=>"22","name"=>["ar"=>"بلطيم","en"=>"Baltim"]],
                ["id"=>"341","governorate_id"=>"22","name"=>["ar"=>"مصيف بلطيم","en"=>"Masief Baltim"]],
                ["id"=>"342","governorate_id"=>"22","name"=>["ar"=>"الحامول","en"=>"Hamol"]],
                ["id"=>"343","governorate_id"=>"22","name"=>["ar"=>"بيلا","en"=>"Bella"]],
                ["id"=>"344","governorate_id"=>"22","name"=>["ar"=>"الرياض","en"=>"Riyadh"]],
                ["id"=>"345","governorate_id"=>"22","name"=>["ar"=>"سيدي سالم","en"=>"Sidi Salm"]],
                ["id"=>"346","governorate_id"=>"22","name"=>["ar"=>"قلين","en"=>"Qellen"]],
                ["id"=>"347","governorate_id"=>"22","name"=>["ar"=>"سيدي غازي","en"=>"Sidi Ghazi"]],
                ["id"=>"348","governorate_id"=>"23","name"=>["ar"=>"مرسى مطروح","en"=>"Marsa Matrouh"]],
                ["id"=>"349","governorate_id"=>"23","name"=>["ar"=>"الحمام","en"=>"El Hamam"]],
                ["id"=>"350","governorate_id"=>"23","name"=>["ar"=>"العلمين","en"=>"Alamein"]],
                ["id"=>"351","governorate_id"=>"23","name"=>["ar"=>"الضبعة","en"=>"Dabaa"]],
                ["id"=>"352","governorate_id"=>"23","name"=>["ar"=>"النجيلة","en"=>"Al-Nagila"]],
                ["id"=>"353","governorate_id"=>"23","name"=>["ar"=>"سيدي براني","en"=>"Sidi Brani"]],
                ["id"=>"354","governorate_id"=>"23","name"=>["ar"=>"السلوم","en"=>"Salloum"]],
                ["id"=>"355","governorate_id"=>"23","name"=>["ar"=>"سيوة","en"=>"Siwa"]],
                ["id"=>"356","governorate_id"=>"23","name"=>["ar"=>"مارينا","en"=>"Marina"]],
                ["id"=>"357","governorate_id"=>"23","name"=>["ar"=>"الساحل الشمالى","en"=>"North Coast"]],
                ["id"=>"358","governorate_id"=>"24","name"=>["ar"=>"الأقصر","en"=>"Luxor"]],
                ["id"=>"359","governorate_id"=>"24","name"=>["ar"=>"الأقصر الجديدة","en"=>"New Luxor"]],
                ["id"=>"360","governorate_id"=>"24","name"=>["ar"=>"إسنا","en"=>"Esna"]],
                ["id"=>"361","governorate_id"=>"24","name"=>["ar"=>"طيبة الجديدة","en"=>"New Tiba"]],
                ["id"=>"362","governorate_id"=>"24","name"=>["ar"=>"الزينية","en"=>"Al ziynia"]],
                ["id"=>"363","governorate_id"=>"24","name"=>["ar"=>"البياضية","en"=>"Al Bayadieh"]],
                ["id"=>"364","governorate_id"=>"24","name"=>["ar"=>"القرنة","en"=>"Al Qarna"]],
                ["id"=>"365","governorate_id"=>"24","name"=>["ar"=>"أرمنت","en"=>"Armant"]],
                ["id"=>"366","governorate_id"=>"24","name"=>["ar"=>"الطود","en"=>"Al Tud"]],
                ["id"=>"367","governorate_id"=>"25","name"=>["ar"=>"قنا","en"=>"Qena"]],
                ["id"=>"368","governorate_id"=>"25","name"=>["ar"=>"قنا الجديدة","en"=>"New Qena"]],
                ["id"=>"369","governorate_id"=>"25","name"=>["ar"=>"ابو طشت","en"=>"Abu Tesht"]],
                ["id"=>"370","governorate_id"=>"25","name"=>["ar"=>"نجع حمادي","en"=>"Nag Hammadi"]],
                ["id"=>"371","governorate_id"=>"25","name"=>["ar"=>"دشنا","en"=>"Deshna"]],
                ["id"=>"372","governorate_id"=>"25","name"=>["ar"=>"الوقف","en"=>"Alwaqf"]],
                ["id"=>"373","governorate_id"=>"25","name"=>["ar"=>"قفط","en"=>"Qaft"]],
                ["id"=>"374","governorate_id"=>"25","name"=>["ar"=>"نقادة","en"=>"Naqada"]],
                ["id"=>"375","governorate_id"=>"25","name"=>["ar"=>"فرشوط","en"=>"Farshout"]],
                ["id"=>"376","governorate_id"=>"25","name"=>["ar"=>"قوص","en"=>"Quos"]],
                ["id"=>"377","governorate_id"=>"26","name"=>["ar"=>"العريش","en"=>"Arish"]],
                ["id"=>"378","governorate_id"=>"26","name"=>["ar"=>"الشيخ زويد","en"=>"Sheikh Zowaid"]],
                ["id"=>"379","governorate_id"=>"26","name"=>["ar"=>"نخل","en"=>"Nakhl"]],
                ["id"=>"380","governorate_id"=>"26","name"=>["ar"=>"رفح","en"=>"Rafah"]],
                ["id"=>"381","governorate_id"=>"26","name"=>["ar"=>"بئر العبد","en"=>"Bir al-Abed"]],
                ["id"=>"382","governorate_id"=>"26","name"=>["ar"=>"الحسنة","en"=>"Al Hasana"]],
                ["id"=>"383","governorate_id"=>"27","name"=>["ar"=>"سوهاج","en"=>"Sohag"]],
                ["id"=>"384","governorate_id"=>"27","name"=>["ar"=>"سوهاج الجديدة","en"=>"Sohag El Gedida"]],
                ["id"=>"385","governorate_id"=>"27","name"=>["ar"=>"أخميم","en"=>"Akhmeem"]],
                ["id"=>"386","governorate_id"=>"27","name"=>["ar"=>"أخميم الجديدة","en"=>"Akhmim El Gedida"]],
                ["id"=>"387","governorate_id"=>"27","name"=>["ar"=>"البلينا","en"=>"Albalina"]],
                ["id"=>"388","governorate_id"=>"27","name"=>["ar"=>"المراغة","en"=>"El Maragha"]],
                ["id"=>"389","governorate_id"=>"27","name"=>["ar"=>"المنشأة","en"=>"almunsha'a"]],
                ["id"=>"390","governorate_id"=>"27","name"=>["ar"=>"دار السلام","en"=>"Dar AISalaam"]],
                ["id"=>"391","governorate_id"=>"27","name"=>["ar"=>"جرجا","en"=>"Gerga"]],
                ["id"=>"392","governorate_id"=>"27","name"=>["ar"=>"جهينة الغربية","en"=>"Jahina Al Gharbia"]],
                ["id"=>"393","governorate_id"=>"27","name"=>["ar"=>"ساقلته","en"=>"Saqilatuh"]],
                ["id"=>"394","governorate_id"=>"27","name"=>["ar"=>"طما","en"=>"Tama"]],
                ["id"=>"395","governorate_id"=>"27","name"=>["ar"=>"طهطا","en"=>"Tahta"]],
                ["id"=>"396","governorate_id"=>"27","name"=>["ar"=>"الكوثر","en"=>"Alkawthar"]]
            ];
            
        foreach($data as $item){
            City::create($item);
        }
    }
}
