<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\City;
class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
                ["id"=>"1","governorate_id"=>"1","name"=>"15 مايو"],
                ["id"=>"2","governorate_id"=>"1","name"=>"الازبكية"],
                ["id"=>"3","governorate_id"=>"1","name"=>"البساتين"],
                ["id"=>"4","governorate_id"=>"1","name"=>"التبين"],
                ["id"=>"5","governorate_id"=>"1","name"=>"الخليفة"],
                ["id"=>"6","governorate_id"=>"1","name"=>"الدراسة"],
                ["id"=>"7","governorate_id"=>"1","name"=>"الدرب الاحمر"],
                ["id"=>"8","governorate_id"=>"1","name"=>"الزاوية الحمراء"],
                ["id"=>"9","governorate_id"=>"1","name"=>"الزيتون"],
                ["id"=>"10","governorate_id"=>"1","name"=>"الساحل"],
                ["id"=>"11","governorate_id"=>"1","name"=>"السلام"],
                ["id"=>"12","governorate_id"=>"1","name"=>"السيدة زينب"],
                ["id"=>"13","governorate_id"=>"1","name"=>"الشرابية"],
                ["id"=>"14","governorate_id"=>"1","name"=>"مدينة الشروق"],
                ["id"=>"15","governorate_id"=>"1","name"=>"الظاهر"],
                ["id"=>"16","governorate_id"=>"1","name"=>"العتبة"],
                ["id"=>"17","governorate_id"=>"1","name"=>"القاهرة الجديدة"],
                ["id"=>"18","governorate_id"=>"1","name"=>"المرج"],
                ["id"=>"19","governorate_id"=>"1","name"=>"عزبة النخل"],
                ["id"=>"20","governorate_id"=>"1","name"=>"المطرية"],
                ["id"=>"21","governorate_id"=>"1","name"=>"المعادى"],
                ["id"=>"22","governorate_id"=>"1","name"=>"المعصرة"],
                ["id"=>"23","governorate_id"=>"1","name"=>"المقطم"],
                ["id"=>"24","governorate_id"=>"1","name"=>"المنيل"],
                ["id"=>"25","governorate_id"=>"1","name"=>"الموسكى"],
                ["id"=>"26","governorate_id"=>"1","name"=>"النزهة"],
                ["id"=>"27","governorate_id"=>"1","name"=>"الوايلى"],
                ["id"=>"28","governorate_id"=>"1","name"=>"باب الشعرية"],
                ["id"=>"29","governorate_id"=>"1","name"=>"بولاق"],
                ["id"=>"30","governorate_id"=>"1","name"=>"جاردن سيتى"],
                ["id"=>"31","governorate_id"=>"1","name"=>"حدائق القبة"],
                ["id"=>"32","governorate_id"=>"1","name"=>"حلوان"],
                ["id"=>"33","governorate_id"=>"1","name"=>"دار السلام"],
                ["id"=>"34","governorate_id"=>"1","name"=>"شبرا"],
                ["id"=>"35","governorate_id"=>"1","name"=>"طره"],
                ["id"=>"36","governorate_id"=>"1","name"=>"عابدين"],
                ["id"=>"37","governorate_id"=>"1","name"=>"عباسية"],
                ["id"=>"38","governorate_id"=>"1","name"=>"عين شمس"],
                ["id"=>"39","governorate_id"=>"1","name"=>"مدينة نصر"],
                ["id"=>"40","governorate_id"=>"1","name"=>"مصر الجديدة"],
                ["id"=>"41","governorate_id"=>"1","name"=>"مصر القديمة"],
                ["id"=>"42","governorate_id"=>"1","name"=>"منشية ناصر"],
                ["id"=>"43","governorate_id"=>"1","name"=>"مدينة بدر"],
                ["id"=>"44","governorate_id"=>"1","name"=>"مدينة العبور"],
                ["id"=>"45","governorate_id"=>"1","name"=>"وسط البلد"],
                ["id"=>"46","governorate_id"=>"1","name"=>"الزمالك"],
                ["id"=>"47","governorate_id"=>"1","name"=>"قصر النيل"],
                ["id"=>"48","governorate_id"=>"1","name"=>"الرحاب"],
                ["id"=>"49","governorate_id"=>"1","name"=>"القطامية"],
                ["id"=>"50","governorate_id"=>"1","name"=>"مدينتي"],
                ["id"=>"51","governorate_id"=>"1","name"=>"روض الفرج"],
                ["id"=>"52","governorate_id"=>"1","name"=>"شيراتون"],
                ["id"=>"53","governorate_id"=>"1","name"=>"الجمالية"],
                ["id"=>"54","governorate_id"=>"1","name"=>"العاشر من رمضان",],
                ["id"=>"55","governorate_id"=>"1","name"=>"الحلمية"],
                ["id"=>"56","governorate_id"=>"1","name"=>"النزهة الجديدة"],
                ["id"=>"57","governorate_id"=>"1","name"=>"العاصمة الإدارية"],
                ["id"=>"58","governorate_id"=>"2","name"=>"الجيزة"],
                ["id"=>"59","governorate_id"=>"2","name"=>"السادس من أكتوبر"],
                ["id"=>"60","governorate_id"=>"2","name"=>"الشيخ زايد"],
                ["id"=>"61","governorate_id"=>"2","name"=>"الحوامدية"],
                ["id"=>"62","governorate_id"=>"2","name"=>"البدرشين"],
                ["id"=>"63","governorate_id"=>"2","name"=>"الصف"],
                ["id"=>"64","governorate_id"=>"2","name"=>"أطفيح"],
                ["id"=>"65","governorate_id"=>"2","name"=>"العياط"],
                ["id"=>"66","governorate_id"=>"2","name"=>"الباويطي"],
                ["id"=>"67","governorate_id"=>"2","name"=>"منشأة القناطر"],
                ["id"=>"68","governorate_id"=>"2","name"=>"أوسيم"],
                ["id"=>"69","governorate_id"=>"2","name"=>"كرداسة"],
                ["id"=>"70","governorate_id"=>"2","name"=>"أبو النمرس"],
                ["id"=>"71","governorate_id"=>"2","name"=>"كفر غطاطي"],
                ["id"=>"72","governorate_id"=>"2","name"=>"منشأة البكاري"],
                ["id"=>"73","governorate_id"=>"2","name"=>"الدقى"],
                ["id"=>"74","governorate_id"=>"2","name"=>"العجوزة"],
                ["id"=>"75","governorate_id"=>"2","name"=>"الهرم"],
                ["id"=>"76","governorate_id"=>"2","name"=>"الوراق"],
                ["id"=>"77","governorate_id"=>"2","name"=>"امبابة"],
                ["id"=>"78","governorate_id"=>"2","name"=>"بولاق الدكرور"],
                ["id"=>"79","governorate_id"=>"2","name"=>"الواحات البحرية"],
                ["id"=>"80","governorate_id"=>"2","name"=>"العمرانية"],
                ["id"=>"81","governorate_id"=>"2","name"=>"المنيب"],
                ["id"=>"82","governorate_id"=>"2","name"=>"بين السرايات"],
                ["id"=>"83","governorate_id"=>"2","name"=>"الكيت كات"],
                ["id"=>"84","governorate_id"=>"2","name"=>"المهندسين"],
                ["id"=>"85","governorate_id"=>"2","name"=>"فيصل"],
                ["id"=>"86","governorate_id"=>"2","name"=>"أبو رواش"],
                ["id"=>"87","governorate_id"=>"2","name"=>"حدائق الأهرام"],
                ["id"=>"88","governorate_id"=>"2","name"=>"الحرانية"],
                ["id"=>"89","governorate_id"=>"2","name"=>"حدائق اكتوبر"],
                ["id"=>"90","governorate_id"=>"2","name"=>"صفط اللبن"],
                ["id"=>"91","governorate_id"=>"2","name"=>"القرية الذكية"],
                ["id"=>"92","governorate_id"=>"2","name"=>"ارض اللواء"],
                ["id"=>"93","governorate_id"=>"3","name"=>"ابو قير"],
                ["id"=>"94","governorate_id"=>"3","name"=>"الابراهيمية"],
                ["id"=>"95","governorate_id"=>"3","name"=>"الأزاريطة"],
                ["id"=>"96","governorate_id"=>"3","name"=>"الانفوشى"],
                ["id"=>"97","governorate_id"=>"3","name"=>"الدخيلة"],
                ["id"=>"98","governorate_id"=>"3","name"=>"السيوف"],
                ["id"=>"99","governorate_id"=>"3","name"=>"العامرية"],
                ["id"=>"100","governorate_id"=>"3","name"=>"اللبان"],
                ["id"=>"101","governorate_id"=>"3","name"=>"المفروزة"],
                ["id"=>"102","governorate_id"=>"3","name"=>"المنتزه"],
                ["id"=>"103","governorate_id"=>"3","name"=>"المنشية"],
                ["id"=>"104","governorate_id"=>"3","name"=>"الناصرية"],
                ["id"=>"105","governorate_id"=>"3","name"=>"امبروزو"],
                ["id"=>"106","governorate_id"=>"3","name"=>"باب شرق"],
                ["id"=>"107","governorate_id"=>"3","name"=>"برج العرب"],
                ["id"=>"108","governorate_id"=>"3","name"=>"ستانلى"],
                ["id"=>"109","governorate_id"=>"3","name"=>"سموحة"],
                ["id"=>"110","governorate_id"=>"3","name"=>"سيدى بشر"],
                ["id"=>"111","governorate_id"=>"3","name"=>"شدس"],
                ["id"=>"112","governorate_id"=>"3","name"=>"غيط العنب"],
                ["id"=>"113","governorate_id"=>"3","name"=>"فلمينج"],
                ["id"=>"114","governorate_id"=>"3","name"=>"فيكتوريا"],
                ["id"=>"115","governorate_id"=>"3","name"=>"كامب شيزار"],
                ["id"=>"116","governorate_id"=>"3","name"=>"كرموز"],
                ["id"=>"117","governorate_id"=>"3","name"=>"محطة الرمل"],
                ["id"=>"118","governorate_id"=>"3","name"=>"مينا البصل"],
                ["id"=>"119","governorate_id"=>"3","name"=>"العصافرة"],
                ["id"=>"120","governorate_id"=>"3","name"=>"العجمي"],
                ["id"=>"121","governorate_id"=>"3","name"=>"بكوس"],
                ["id"=>"122","governorate_id"=>"3","name"=>"بولكلي"],
                ["id"=>"123","governorate_id"=>"3","name"=>"كليوباترا"],
                ["id"=>"124","governorate_id"=>"3","name"=>"جليم"],
                ["id"=>"125","governorate_id"=>"3","name"=>"المعمورة"],
                ["id"=>"126","governorate_id"=>"3","name"=>"المندرة"],
                ["id"=>"127","governorate_id"=>"3","name"=>"محرم بك"],
                ["id"=>"128","governorate_id"=>"3","name"=>"الشاطبي"],
                ["id"=>"129","governorate_id"=>"3","name"=>"سيدي جابر"],
                ["id"=>"130","governorate_id"=>"3","name"=>"الساحل الشمالي"],
                ["id"=>"131","governorate_id"=>"3","name"=>"الحضرة"],
                ["id"=>"132","governorate_id"=>"3","name"=>"العطارين"],
                ["id"=>"133","governorate_id"=>"3","name"=>"سيدي كرير"],
                ["id"=>"134","governorate_id"=>"3","name"=>"الجمرك"],
                ["id"=>"135","governorate_id"=>"3","name"=>"المكس"],
                ["id"=>"136","governorate_id"=>"3","name"=>"مارينا"],
                ["id"=>"137","governorate_id"=>"4","name"=>"المنصورة"],
                ["id"=>"138","governorate_id"=>"4","name"=>"طلخا"],
                ["id"=>"139","governorate_id"=>"4","name"=>"ميت غمر"],
                ["id"=>"140","governorate_id"=>"4","name"=>"دكرنس"],
                ["id"=>"141","governorate_id"=>"4","name"=>"أجا"],
                ["id"=>"142","governorate_id"=>"4","name"=>"منية النصر"],
                ["id"=>"143","governorate_id"=>"4","name"=>"السنبلاوين"],
                ["id"=>"144","governorate_id"=>"4","name"=>"الكردي"],
                ["id"=>"145","governorate_id"=>"4","name"=>"بني عبيد"],
                ["id"=>"146","governorate_id"=>"4","name"=>"المنزلة"],
                ["id"=>"147","governorate_id"=>"4","name"=>"تمي الأمديد"],
                ["id"=>"148","governorate_id"=>"4","name"=>"الجمالية"],
                ["id"=>"149","governorate_id"=>"4","name"=>"شربين"],
                ["id"=>"150","governorate_id"=>"4","name"=>"المطرية"],
                ["id"=>"151","governorate_id"=>"4","name"=>"بلقاس"],
                ["id"=>"152","governorate_id"=>"4","name"=>"ميت سلسيل"],
                ["id"=>"153","governorate_id"=>"4","name"=>"جمصة"],
                ["id"=>"154","governorate_id"=>"4","name"=>"محلة دمنة"],
                ["id"=>"155","governorate_id"=>"4","name"=>"نبروه"],
                ["id"=>"156","governorate_id"=>"5","name"=>"الغردقة"],
                ["id"=>"157","governorate_id"=>"5","name"=>"رأس غارب"],
                ["id"=>"158","governorate_id"=>"5","name"=>"سفاجا"],
                ["id"=>"159","governorate_id"=>"5","name"=>"القصير"],
                ["id"=>"160","governorate_id"=>"5","name"=>"مرسى علم"],
                ["id"=>"161","governorate_id"=>"5","name"=>"الشلاتين"],
                ["id"=>"162","governorate_id"=>"5","name"=>"حلايب"],
                ["id"=>"163","governorate_id"=>"5","name"=>"الدهار"],
                ["id"=>"164","governorate_id"=>"6","name"=>"دمنهور"],
                ["id"=>"165","governorate_id"=>"6","name"=>"كفر الدوار"],
                ["id"=>"166","governorate_id"=>"6","name"=>"رشيد"],
                ["id"=>"167","governorate_id"=>"6","name"=>"إدكو"],
                ["id"=>"168","governorate_id"=>"6","name"=>"أبو المطامير"],
                ["id"=>"169","governorate_id"=>"6","name"=>"أبو حمص"],
                ["id"=>"170","governorate_id"=>"6","name"=>"الدلنجات"],
                ["id"=>"171","governorate_id"=>"6","name"=>"المحمودية"],
                ["id"=>"172","governorate_id"=>"6","name"=>"الرحمانية"],
                ["id"=>"173","governorate_id"=>"6","name"=>"إيتاي البارود"],
                ["id"=>"174","governorate_id"=>"6","name"=>"حوش عيسى"],
                ["id"=>"175","governorate_id"=>"6","name"=>"شبراخيت"],
                ["id"=>"176","governorate_id"=>"6","name"=>"كوم حمادة"],
                ["id"=>"177","governorate_id"=>"6","name"=>"بدر"],
                ["id"=>"178","governorate_id"=>"6","name"=>"وادي النطرون"],
                ["id"=>"179","governorate_id"=>"6","name"=>"النوبارية الجديدة"],
                ["id"=>"180","governorate_id"=>"6","name"=>"النوبارية"],
                ["id"=>"181","governorate_id"=>"7","name"=>"الفيوم"],
                ["id"=>"182","governorate_id"=>"7","name"=>"الفيوم الجديدة"],
                ["id"=>"183","governorate_id"=>"7","name"=>"طامية"],
                ["id"=>"184","governorate_id"=>"7","name"=>"سنورس"],
                ["id"=>"185","governorate_id"=>"7","name"=>"إطسا"],
                ["id"=>"186","governorate_id"=>"7","name"=>"إبشواي"],
                ["id"=>"187","governorate_id"=>"7","name"=>"يوسف الصديق"],
                ["id"=>"188","governorate_id"=>"7","name"=>"الحادقة"],
                ["id"=>"189","governorate_id"=>"7","name"=>"اطسا"],
                ["id"=>"190","governorate_id"=>"7","name"=>"الجامعة"],
                ["id"=>"191","governorate_id"=>"7","name"=>"السيالة"],
                ["id"=>"192","governorate_id"=>"8","name"=>"طنطا"],
                ["id"=>"193","governorate_id"=>"8","name"=>"المحلة الكبرى"],
                ["id"=>"194","governorate_id"=>"8","name"=>"كفر الزيات"],
                ["id"=>"195","governorate_id"=>"8","name"=>"زفتى"],
                ["id"=>"196","governorate_id"=>"8","name"=>"السنطة"],
                ["id"=>"197","governorate_id"=>"8","name"=>"قطور"],
                ["id"=>"198","governorate_id"=>"8","name"=>"بسيون"],
                ["id"=>"199","governorate_id"=>"8","name"=>"سمنود"],
                ["id"=>"200","governorate_id"=>"9","name"=>"الإسماعيلية"],
                ["id"=>"201","governorate_id"=>"9","name"=>"فايد"],
                ["id"=>"202","governorate_id"=>"9","name"=>"القنطرة شرق"],
                ["id"=>"203","governorate_id"=>"9","name"=>"القنطرة غرب"],
                ["id"=>"204","governorate_id"=>"9","name"=>"التل الكبير"],
                ["id"=>"205","governorate_id"=>"9","name"=>"أبو صوير"],
                ["id"=>"206","governorate_id"=>"9","name"=>"القصاصين الجديدة"],
                ["id"=>"207","governorate_id"=>"9","name"=>"نفيشة"],
                ["id"=>"208","governorate_id"=>"9","name"=>"الشيخ زايد"],
                ["id"=>"209","governorate_id"=>"10","name"=>"شبين الكوم"],
                ["id"=>"210","governorate_id"=>"10","name"=>"مدينة السادات"],
                ["id"=>"211","governorate_id"=>"10","name"=>"منوف"],
                ["id"=>"212","governorate_id"=>"10","name"=>"سرس الليان"],
                ["id"=>"213","governorate_id"=>"10","name"=>"أشمون"],
                ["id"=>"214","governorate_id"=>"10","name"=>"الباجور"],
                ["id"=>"215","governorate_id"=>"10","name"=>"قويسنا"],
                ["id"=>"216","governorate_id"=>"10","name"=>"بركة السبع"],
                ["id"=>"217","governorate_id"=>"10","name"=>"تلا"],
                ["id"=>"218","governorate_id"=>"10","name"=>"الشهداء"],
                ["id"=>"219","governorate_id"=>"11","name"=>"المنيا"],
                ["id"=>"220","governorate_id"=>"11","name"=>"المنيا الجديدة"],
                ["id"=>"221","governorate_id"=>"11","name"=>"العدوة"],
                ["id"=>"222","governorate_id"=>"11","name"=>"مغاغة"],
                ["id"=>"223","governorate_id"=>"11","name"=>"بني مزار"],
                ["id"=>"224","governorate_id"=>"11","name"=>"مطاي"],
                ["id"=>"225","governorate_id"=>"11","name"=>"سمالوط"],
                ["id"=>"226","governorate_id"=>"11","name"=>"المدينة الفكرية"],
                ["id"=>"227","governorate_id"=>"11","name"=>"ملوي"],
                ["id"=>"228","governorate_id"=>"11","name"=>"دير مواس"],
                ["id"=>"229","governorate_id"=>"11","name"=>"ابو قرقاص"],
                ["id"=>"230","governorate_id"=>"11","name"=>"ارض سلطان"],
                ["id"=>"231","governorate_id"=>"12","name"=>"بنها"],
                ["id"=>"232","governorate_id"=>"12","name"=>"قليوب"],
                ["id"=>"233","governorate_id"=>"12","name"=>"شبرا الخيمة"],
                ["id"=>"234","governorate_id"=>"12","name"=>"القناطر الخيرية"],
                ["id"=>"235","governorate_id"=>"12","name"=>"الخانكة"],
                ["id"=>"236","governorate_id"=>"12","name"=>"كفر شكر"],
                ["id"=>"237","governorate_id"=>"12","name"=>"طوخ"],
                ["id"=>"238","governorate_id"=>"12","name"=>"قها"],
                ["id"=>"239","governorate_id"=>"12","name"=>"العبور"],
                ["id"=>"240","governorate_id"=>"12","name"=>"الخصوص"],
                ["id"=>"241","governorate_id"=>"12","name"=>"شبين القناطر"],
                ["id"=>"242","governorate_id"=>"12","name"=>"مسطرد"],
                ["id"=>"243","governorate_id"=>"13","name"=>"الخارجة"],
                ["id"=>"244","governorate_id"=>"13","name"=>"باريس"],
                ["id"=>"245","governorate_id"=>"13","name"=>"موط"],
                ["id"=>"246","governorate_id"=>"13","name"=>"الفرافرة"],
                ["id"=>"247","governorate_id"=>"13","name"=>"بلاط"],
                ["id"=>"248","governorate_id"=>"13","name"=>"الداخلة"],
                ["id"=>"249","governorate_id"=>"14","name"=>"السويس"],
                ["id"=>"250","governorate_id"=>"14","name"=>"الجناين"],
                ["id"=>"251","governorate_id"=>"14","name"=>"عتاقة"],
                ["id"=>"252","governorate_id"=>"14","name"=>"العين السخنة"],
                ["id"=>"253","governorate_id"=>"14","name"=>"فيصل"],
                ["id"=>"254","governorate_id"=>"15","name"=>"أسوان"],
                ["id"=>"255","governorate_id"=>"15","name"=>"أسوان الجديدة"],
                ["id"=>"256","governorate_id"=>"15","name"=>"دراو"],
                ["id"=>"257","governorate_id"=>"15","name"=>"كوم أمبو"],
                ["id"=>"258","governorate_id"=>"15","name"=>"نصر النوبة"],
                ["id"=>"259","governorate_id"=>"15","name"=>"كلابشة"],
                ["id"=>"260","governorate_id"=>"15","name"=>"إدفو"],
                ["id"=>"261","governorate_id"=>"15","name"=>"الرديسية"],
                ["id"=>"262","governorate_id"=>"15","name"=>"البصيلية"],
                ["id"=>"263","governorate_id"=>"15","name"=>"السباعية"],
                ["id"=>"264","governorate_id"=>"15","name"=>"ابوسمبل السياحية",],
                ["id"=>"265","governorate_id"=>"15","name"=>"مرسى علم"],
                ["id"=>"266","governorate_id"=>"16","name"=>"أسيوط"],
                ["id"=>"267","governorate_id"=>"16","name"=>"أسيوط الجديدة"],
                ["id"=>"268","governorate_id"=>"16","name"=>"ديروط"],
                ["id"=>"269","governorate_id"=>"16","name"=>"منفلوط"],
                ["id"=>"270","governorate_id"=>"16","name"=>"القوصية"],
                ["id"=>"271","governorate_id"=>"16","name"=>"أبنوب"],
                ["id"=>"272","governorate_id"=>"16","name"=>"أبو تيج"],
                ["id"=>"273","governorate_id"=>"16","name"=>"الغنايم"],
                ["id"=>"274","governorate_id"=>"16","name"=>"ساحل سليم"],
                ["id"=>"275","governorate_id"=>"16","name"=>"البداري"],
                ["id"=>"276","governorate_id"=>"16","name"=>"صدفا"],
                ["id"=>"277","governorate_id"=>"17","name"=>"بني سويف"],
                ["id"=>"278","governorate_id"=>"17","name"=>"بني سويف الجديدة"],
                ["id"=>"279","governorate_id"=>"17","name"=>"الواسطى"],
                ["id"=>"280","governorate_id"=>"17","name"=>"ناصر"],
                ["id"=>"281","governorate_id"=>"17","name"=>"إهناسيا"],
                ["id"=>"282","governorate_id"=>"17","name"=>"ببا"],
                ["id"=>"283","governorate_id"=>"17","name"=>"الفشن"],
                ["id"=>"284","governorate_id"=>"17","name"=>"سمسطا"],
                ["id"=>"285","governorate_id"=>"17","name"=>"الاباصيرى"],
                ["id"=>"286","governorate_id"=>"17","name"=>"مقبل"],
                ["id"=>"287","governorate_id"=>"18","name"=>"بورسعيد"],
                ["id"=>"288","governorate_id"=>"18","name"=>"بورفؤاد"],
                ["id"=>"289","governorate_id"=>"18","name"=>"العرب"],
                ["id"=>"290","governorate_id"=>"18","name"=>"حى الزهور"],
                ["id"=>"291","governorate_id"=>"18","name"=>"حى الشرق"],
                ["id"=>"292","governorate_id"=>"18","name"=>"حى الضواحى"],
                ["id"=>"293","governorate_id"=>"18","name"=>"حى المناخ"],
                ["id"=>"294","governorate_id"=>"18","name"=>"حى مبارك"],
                ["id"=>"295","governorate_id"=>"19","name"=>"دمياط"],
                ["id"=>"296","governorate_id"=>"19","name"=>"دمياط الجديدة"],
                ["id"=>"297","governorate_id"=>"19","name"=>"رأس البر"],
                ["id"=>"298","governorate_id"=>"19","name"=>"فارسكور"],
                ["id"=>"299","governorate_id"=>"19","name"=>"الزرقا"],
                ["id"=>"300","governorate_id"=>"19","name"=>"السرو"],
                ["id"=>"301","governorate_id"=>"19","name"=>"الروضة"],
                ["id"=>"302","governorate_id"=>"19","name"=>"كفر البطيخ"],
                ["id"=>"303","governorate_id"=>"19","name"=>"عزبة البرج"],
                ["id"=>"304","governorate_id"=>"19","name"=>"ميت أبو غالب"],
                ["id"=>"305","governorate_id"=>"19","name"=>"كفر سعد"],
                ["id"=>"306","governorate_id"=>"20","name"=>"الزقازيق"],
                ["id"=>"307","governorate_id"=>"20","name"=>"العاشر من رمضان"],
                ["id"=>"308","governorate_id"=>"20","name"=>"منيا القمح"],
                ["id"=>"309","governorate_id"=>"20","name"=>"بلبيس"],
                ["id"=>"310","governorate_id"=>"20","name"=>"مشتول السوق"],
                ["id"=>"311","governorate_id"=>"20","name"=>"القنايات"],
                ["id"=>"312","governorate_id"=>"20","name"=>"أبو حماد"],
                ["id"=>"313","governorate_id"=>"20","name"=>"القرين"],
                ["id"=>"314","governorate_id"=>"20","name"=>"ههيا"],
                ["id"=>"315","governorate_id"=>"20","name"=>"أبو كبير"],
                ["id"=>"316","governorate_id"=>"20","name"=>"فاقوس"],
                ["id"=>"317","governorate_id"=>"20","name"=>"الصالحية الجديدة",],
                ["id"=>"318","governorate_id"=>"20","name"=>"الإبراهيمية"],
                ["id"=>"319","governorate_id"=>"20","name"=>"ديرب نجم"],
                ["id"=>"320","governorate_id"=>"20","name"=>"كفر صقر"],
                ["id"=>"321","governorate_id"=>"20","name"=>"أولاد صقر"],
                ["id"=>"322","governorate_id"=>"20","name"=>"الحسينية"],
                ["id"=>"323","governorate_id"=>"20","name"=>"صان الحجر القبلية",],
                ["id"=>"324","governorate_id"=>"20","name"=>"منشأة أبو عمر"],
                ["id"=>"325","governorate_id"=>"21","name"=>"الطور"],
                ["id"=>"326","governorate_id"=>"21","name"=>"شرم الشيخ"],
                ["id"=>"327","governorate_id"=>"21","name"=>"دهب"],
                ["id"=>"328","governorate_id"=>"21","name"=>"نويبع"],
                ["id"=>"329","governorate_id"=>"21","name"=>"طابا"],
                ["id"=>"330","governorate_id"=>"21","name"=>"سانت كاترين"],
                ["id"=>"331","governorate_id"=>"21","name"=>"أبو رديس"],
                ["id"=>"332","governorate_id"=>"21","name"=>"أبو زنيمة"],
                ["id"=>"333","governorate_id"=>"21","name"=>"رأس سدر"],
                ["id"=>"334","governorate_id"=>"22","name"=>"كفر الشيخ"],
                ["id"=>"335","governorate_id"=>"22","name"=>"وسط البلد كفر الشيخ",   ],
                ["id"=>"336","governorate_id"=>"22","name"=>"دسوق"],
                ["id"=>"337","governorate_id"=>"22","name"=>"فوه"],
                ["id"=>"338","governorate_id"=>"22","name"=>"مطوبس"],
                ["id"=>"339","governorate_id"=>"22","name"=>"برج البرلس"],
                ["id"=>"340","governorate_id"=>"22","name"=>"بلطيم"],
                ["id"=>"341","governorate_id"=>"22","name"=>"مصيف بلطيم"],
                ["id"=>"342","governorate_id"=>"22","name"=>"الحامول"],
                ["id"=>"343","governorate_id"=>"22","name"=>"بيلا"],
                ["id"=>"344","governorate_id"=>"22","name"=>"الرياض"],
                ["id"=>"345","governorate_id"=>"22","name"=>"سيدي سالم"],
                ["id"=>"346","governorate_id"=>"22","name"=>"قلين"],
                ["id"=>"347","governorate_id"=>"22","name"=>"سيدي غازي"],
                ["id"=>"348","governorate_id"=>"23","name"=>"مرسى مطروح"],
                ["id"=>"349","governorate_id"=>"23","name"=>"الحمام"],
                ["id"=>"350","governorate_id"=>"23","name"=>"العلمين"],
                ["id"=>"351","governorate_id"=>"23","name"=>"الضبعة"],
                ["id"=>"352","governorate_id"=>"23","name"=>"النجيلة"],
                ["id"=>"353","governorate_id"=>"23","name"=>"سيدي براني"],
                ["id"=>"354","governorate_id"=>"23","name"=>"السلوم"],
                ["id"=>"355","governorate_id"=>"23","name"=>"سيوة"],
                ["id"=>"356","governorate_id"=>"23","name"=>"مارينا"],
                ["id"=>"357","governorate_id"=>"23","name"=>"الساحل الشمالى"],
                ["id"=>"358","governorate_id"=>"24","name"=>"الأقصر"],
                ["id"=>"359","governorate_id"=>"24","name"=>"الأقصر الجديدة"],
                ["id"=>"360","governorate_id"=>"24","name"=>"إسنا"],
                ["id"=>"361","governorate_id"=>"24","name"=>"طيبة الجديدة"],
                ["id"=>"362","governorate_id"=>"24","name"=>"الزينية"],
                ["id"=>"363","governorate_id"=>"24","name"=>"البياضية"],
                ["id"=>"364","governorate_id"=>"24","name"=>"القرنة"],
                ["id"=>"365","governorate_id"=>"24","name"=>"أرمنت"],
                ["id"=>"366","governorate_id"=>"24","name"=>"الطود"],
                ["id"=>"367","governorate_id"=>"25","name"=>"قنا"],
                ["id"=>"368","governorate_id"=>"25","name"=>"قنا الجديدة"],
                ["id"=>"369","governorate_id"=>"25","name"=>"ابو طشت"],
                ["id"=>"370","governorate_id"=>"25","name"=>"نجع حمادي"],
                ["id"=>"371","governorate_id"=>"25","name"=>"دشنا"],
                ["id"=>"372","governorate_id"=>"25","name"=>"الوقف"],
                ["id"=>"373","governorate_id"=>"25","name"=>"قفط"],
                ["id"=>"374","governorate_id"=>"25","name"=>"نقادة"],
                ["id"=>"375","governorate_id"=>"25","name"=>"فرشوط"],
                ["id"=>"376","governorate_id"=>"25","name"=>"قوص"],
                ["id"=>"377","governorate_id"=>"26","name"=>"العريش"],
                ["id"=>"378","governorate_id"=>"26","name"=>"الشيخ زويد"],
                ["id"=>"379","governorate_id"=>"26","name"=>"نخل"],
                ["id"=>"380","governorate_id"=>"26","name"=>"رفح"],
                ["id"=>"381","governorate_id"=>"26","name"=>"بئر العبد"],
                ["id"=>"382","governorate_id"=>"26","name"=>"الحسنة"],
                ["id"=>"383","governorate_id"=>"27","name"=>"سوهاج"],
                ["id"=>"384","governorate_id"=>"27","name"=>"سوهاج الجديدة"],
                ["id"=>"385","governorate_id"=>"27","name"=>"أخميم"],
                ["id"=>"386","governorate_id"=>"27","name"=>"أخميم الجديدة"],
                ["id"=>"387","governorate_id"=>"27","name"=>"البلينا"],
                ["id"=>"388","governorate_id"=>"27","name"=>"المراغة"],
                ["id"=>"389","governorate_id"=>"27","name"=>"المنشأة"],
                ["id"=>"390","governorate_id"=>"27","name"=>"دار السلام"],
                ["id"=>"391","governorate_id"=>"27","name"=>"جرجا"],
                ["id"=>"392","governorate_id"=>"27","name"=>"جهينة الغربية"],
                ["id"=>"393","governorate_id"=>"27","name"=>"ساقلته"],
                ["id"=>"394","governorate_id"=>"27","name"=>"طما"],
                ["id"=>"395","governorate_id"=>"27","name"=>"طهطا"],
                ["id"=>"396","governorate_id"=>"27","name"=>"الكوثر"]
            ];
            
        foreach($data as $item){
            City::create($item);
        }
    }
}
